# Generated by Django 5.0.2 on 2024-02-12 22:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='imple1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imple2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imple3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imple4',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imple5',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='imple6',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='proj_pics/'),
            preserve_default=False,
        ),
    ]
