# Generated by Django 5.0.2 on 2024-02-13 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0002_remove_projects_imple1_remove_projects_imple2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
