# Generated by Django 5.0.2 on 2024-02-13 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0003_projects_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='desc',
        ),
        migrations.AddField(
            model_name='projects',
            name='lifecycle',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='technologies',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='versionControl',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
